blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: "https://github.com/The-LukeZ/upvote-engine/discussions"
    about: Please ask usage questions or get help in the discussions.
